# Generated by Django 2.1 on 2021-01-03 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiM02_users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('emp_codigo', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('emp_nombres_apellidos', models.TextField()),
                ('plaza', models.TextField()),
                ('puesto', models.TextField()),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('ubi_codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='empleado',
            name='ubi_codigo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiM02_users.Ubicacion'),
        ),
    ]
