# Generated by Django 2.1 on 2020-11-18 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('idRol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
    ]
