# Generated by Django 2.1 on 2020-11-18 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiM01_login', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rol',
        ),
    ]
